name: New Pull request Open
on: workflow_dispatch

jobs:
  make_metadata:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Check out branch
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Build metadata
        run: |
          make metadata
      - name: Commit metadata.json file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: metadata.json
          commit_message: update metadata.json
  